### ISSUE TITLE
Update bug or misunderstood logic?

### ISSUE THREAD

**Issue by antonpenev** [Urbiwanus/ionic-app-loader#1]
Hey,
FIrst congrats for the repo! If you still support this could you help me get it working?
I've cloned it. Did the 'installation' steps. Emulate the code. First time loading is working fine.  
But when I make change on one of the templates (f.x. browse.html), and then run `grunt build`, click the 'CheckForUpdates` button in the menu. The changes in the template are not applied. Can you help me with the reason for this or what could I possibly doing wrong? 
Thanks.

**Comment by Urbiwanus** [comment]
HI the repo is a bit outdated. I will commit a working version asap

**Comment by chauthai** [comment]
@antonpenev 
I've forked the repo and updated the files to a working state. At the moment only .js-files work.
Have a look: https://github.com/chauthai/ionic-app-loader.git

**Comment by chauthai** [comment]
@Urbiwanus I've created a pull request. Please review the changes to apply it! 
Thanks ;-)
